project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "EDUC 315: Principles of Teaching Math and Science in Urban Classrooms II (Grades 4-6)"
  description: "Course site for EDUC 315 at Howard University"
  site-url: "https://educ315-fa25.github.io"
  
  repo-url: "https://github.com/professornaite/educ315-fa25/"
  
  open-graph: true

  page-footer:
    right: "This page was built by Nathan Alexander, PhD in [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Nathan Alexander"
    background: "#ccb6b1"
   
  sidebar:
    background: "#ccb6b1"
    logo: "img/gladys-west.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://professornaite.github.io/educ315-fa25/
        text: "GitHub organization"
      - icon: code-square
        href: https://canvas.howard.edu/courses/53402
        text: "Canvas site"
  
    style: "docked"
    search: true
    collapse-level: 1
    contents:  
    - section: "Course information"
      contents:
        - href: index.qmd
          text: Course landing page
        - href: who.qmd
          text: Who is in the site photo?
        - href: course-overview.qmd
          text: Overview
        - href: assignments.qmd
          text: Assignments
    - section: "Modules"
      contents:
        - href: modules/module01.qmd
          text: Module 1
        - href: modules/module02.qmd
          text: Module 2
        - href: modules/module03.qmd
          text: Module 3
        - href: modules/module04.qmd
          text: Module 4
        - href: modules/module05.qmd
          text: Module 5
    - section: "Assignment rubrics"
      contents:
        - href: modules/historical.qmd
          text: Historical STEM figure
        - href: modules/math-lesson1.qmd
          text: Mathematics Lesson
        - href: files/sample-assessment.Rmd
          text: Sample Math Lesson Rubric
    - section: "Field experience"
      contents:
        - href: field/expectations.qmd
          text: Expectations
        - href: field/weekly.qmd
          text: Weekly schedules
    - section: "Standards and curricula"
      contents: 
        - href: standards/common.qmd
          text: Common Core State Standards - Mathematics
        - href: standards/osse.qmd
          text: Office of the State Superintendent of Education (OSSE)
        - href: standards/umoja.qmd
          text: Umoja Curriculum
        - href: standards/freedom.qmd
          text: Freedom School Curriculum

format:
  html:
    theme:
      light: [spacelab, style/data202.scss]
      dark: [spacelab, style/data202.scss, style/theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    callout-appearance: simple
    colorlinnks: true
    code-copy: true
    code-overflow: wrap
    toc: true

execute: 
  freeze: auto
    
editor: visual