---
title: "Classroom Resources"
subtitle: "Office of the State Superintendent of Education - DC.gov" 
---


Text for this page was taken from osse.dc.gov:

Science, Technology, Engineering, and Math (STEM)

DC recognizes the importance of STEM as part of a well-rounded educational experience. STEM skills and knowledge are not only valuable components to a solid academic program, but also core fundamentals for life experience. STEM skills and knowledge help students develop logic, problem-solving, and critical thinking skills that can be used in every discipline and that enable them to compete in the continually growing high-tech job sector.  As such, DC strives to improve STEM opportunities for all its students and has established the following statewide goals for STEM:

Goal 1: 
To prepare all students in DC to graduate high school with a college- and career-ready mastery of math, science, engineering and technology
    
Goal 2: 
To increase the number of DC students who major in STEM fields in college and enter STEM careers


Find more information by clicking [here](https://osse.dc.gov/page/classroom-resources-educators)


